# Generated by Django 6.0.1 on 2026-01-16 07:19

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('summary', models.JSONField(blank=True, default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='Snapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_filename', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('is_active', models.BooleanField(default=True)),
                ('fw_rules', models.JSONField(blank=True, default=list)),
                ('nat_rules', models.JSONField(blank=True, default=list)),
                ('policy_rules_count', models.PositiveIntegerField(default=0)),
                ('nat_rules_count', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('processing', 'в процессе'), ('ready', 'готово'), ('error', 'ошибка')], default='ready', max_length=16)),
                ('error_text', models.TextField(blank=True, default='')),
            ],
        ),
        migrations.CreateModel(
            name='Anomaly',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('scope', models.CharField(choices=[('fw', 'FilterRules'), ('nat', 'NatRules')], max_length=8)),
                ('code', models.CharField(blank=True, default='', max_length=64)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('severity', models.CharField(choices=[('low', 'низкая'), ('medium', 'средняя'), ('high', 'высокая'), ('critical', 'критическая')], default='medium', max_length=16)),
                ('rule_index', models.IntegerField(blank=True, null=True)),
                ('rule_name', models.CharField(blank=True, default='', max_length=255)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anomalies', to='analyzer.report')),
            ],
        ),
        migrations.AddField(
            model_name='report',
            name='snapshot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='analyzer.snapshot'),
        ),
    ]
